<?php
/*
 * HightailYouSendItAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace HightailYouSendItAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class. 
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://test2-api.yousendit.com/dpi';

    /**
     * @todo Replace the $apiKey with an appropriate value
     */
    public static $apiKey = 'TODO: Replace';

}
